# Generated by Django 4.0.4 on 2022-06-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
